// Aula08/frontend/react/src/App.tsx
import { useState } from "react";
import SignupForm from "./SignupForm";

function App() {
	const [form, setForm] = useState(new SignupForm());

	function reload (fn: any) {
		if (fn) fn();
		setForm(clone(form));
	}

	function clone(obj: any) {
		var copy = new obj.constructor;
		for (var attr in obj) {
			if (obj.hasOwnProperty(attr)) copy[attr] = obj[attr];
		}
		return copy;
	}

	return (
		<div>
			<div>{ form.step }</div>
			<div>{ form.getProgress() }</div>
			{ form.step === 1 && <div>
				<div>
					<input className="input-name" value={form.name} onChange={(e) => reload(() => form.name = e.target.value)}/>
				</div>
				<div>
					<input className="input-email" value={form.email} onChange={(e) => reload(() => form.email = e.target.value)}/>
				</div>
				<div>
					<input className="input-document" value={form.document} onChange={(e) => reload(() => form.document = e.target.value)}/>
				</div>
			</div>}
			{ form.step === 2 && <div>
				<div>
					<input className="input-password" value={form.password} onChange={(e) => reload(() => form.password = e.target.value)}/>
				</div>
				<div>
					<input className="input-confirm-password" value={form.confirmPassword} onChange={(e) => reload(() => form.confirmPassword = e.target.value)}/>
				</div>
			</div>}
			<span className="span-error">{ form.error }</span>
			<button className="button-fill" onClick={() => reload(() => form.fill())}>Fill</button>
			{ form.step === 2 && <button className="button-previous" onClick={() => reload(() => form.previous())}>Previous</button>}
			{ form.step === 1 && <button className="button-next" onClick={() => reload(() => form.next())}>Next</button>}
			{ form.step === 2 && <button className="button-confirm" onClick={() => reload(() => form.confirm())}>Confirm</button>}
		</div>
	)
}

export default App

// Aula08/frontend/vue/src/App.vue
<script setup lang="ts">
  import { inject, ref } from 'vue';
  import type AccountGateway from './AccountGateway';
  import SignupForm from './SignupForm';

  const form = ref(new SignupForm());
  const accountGateway = inject("accountGateway") as AccountGateway;
  form.value.register("signup", async (input: any) => {
    const output = await accountGateway.save(input);
    if (output.accountId) {
      form.value.accountId = output.accountId;
      form.value.message = "success";
    } else {
      form.value.message = output.message;
    }
  });
  
</script>

<template>
  <div>
    <div>
      <span>Step</span>
      <span class="span-step">{{ form.step }}</span>
    </div>
    <div>
      <span>Progress</span>
      <span class="span-progress">{{ form.getProgress() }}%</span>
    </div>
    <div v-if="form.step === 1">
      <div>
        <input class="input-name" type="text" v-model="form.name" placeholder="Name"/>
      </div>
      <div>
        <input class="input-email"  type="text" v-model="form.email" placeholder="Email"/>
      </div>
      <div>
        <input class="input-document"  type="text" v-model="form.document" placeholder="Document"/>
      </div>
    </div>
    <div v-if="form.step === 2">
      <div>
        <input class="input-password"  type="text" v-model="form.password" placeholder="Password"/>
      </div>
      <div>
        <input class="input-confirm-password"  type="text" v-model="form.confirmPassword" placeholder="Confirm Password"/>
      </div>
    </div>
    <button v-if="form.step === 2" class="button-signup" @click="form.signup()">Signup</button>
    <button v-if="form.step === 2" class="button-previous" @click="form.previous()">Previous</button>
    <button v-if="form.step === 1" class="button-next" @click="form.next()">Next</button>
    <button class="button-signup" @click="form.populate()">Populate</button>
    <span class="span-account-id">{{ form.accountId }}</span>
    <span class="span-message">{{ form.message }}</span>
  </div>
</template>

<style scoped>
</style>
